apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: my-issuer
    namespace: hyunsub
spec:
    acme:
        # ca 서버 주소. 해당 서버를 통해 인증서 발행
        server: https://acme-v02.api.letsencrypt.org/directory
        # 인증서 만료 또는 갱신 필요시 알람 email
        email: didakd22@naver.com
        privateKeySecretRef:
            # 인증서를 발급받기 위해 ca와 통신시에 사용되는 Secret 이름
            # 해당 name은 크게 중요한 name이 아니래.
            name: my-issuer
        solvers:
            - http01:
                  ingress:
                      # 도메인의 소유권을 확인하기 위해 cert-manager는 nginx기반의 ingress controller를 활용해 검증한다는 의미
                      # 이것도 크게 중요한건 아니래.
                      class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: server-esktest098-com-tls
    namespace: hyunsub
spec:
    # cert-manager가 아래 secretName에서 지정한 이름으로 Secret을 생성
    # 이 secret name이 중요하다. CA 기관으로부터 인증서를 받고 시크릿에다가 인증서와 비밀키를 넣어둔다고 했는데
    # 이 시크릿에다가 지정해 놓는 거임. 그래서 INGRESS에서 정의한 secretName과 일치해야 함.
    secretName: server-esktest098-com-tls
    duration: 2160h #90day / 인증서의 유효 기간
    renewBefore: 360h #before 15day / 갱신 주기
    issuerRef:
        # ClusterIssuer의 이름을 참조
        name: my-issuer
        kind: ClusterIssuer
    commonName: server.esktest098.store # 대표하는 도메인이 뭐냐! 라는 의미다.
    dnsNames:
        # 추가적인 서브도메인을 추가하고 싶은경우에 여기에 나열
        # 만약 서버1도 있고 2도 있고 여러 개가 있다면 여기에 다 적어주면 된다.
        # 여기다가 적어놔야 CA 기관에서 이 도메인으로 http 요청을 보내서 소유자인지 아닌지를 체크한다.
        - server.esktest098.store
