apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: order-backend
    namespace: argocd # argocd의 namespace
spec:
    project: default
    source:
        repoURL: https://github.com/HyunSubb/K8s # 여기는 argocd가 바라볼 깃허브 레포의 위치를 적어줘야 한다.
        targetRevision: main
        path: 2.ordersystem/k8s/k8s-ordersystem # 여기는 argocdr가 바라볼 폴더의 경로를 적어주면 된다.
    destination:
        # https://kubernetes.default.svc: 이는 Argo CD 자체가 설치된 클러스터의 내부 주소
        server: https://kubernetes.default.svc
        namespace: hyunsub # 여긴 우리의 namespace를 적어주면 됨. 하나의 Application당 하나의 namespace만을 바라본다.
    syncPolicy:
        # Argo CD가 사람이 명령 안 해도 자동으로 GitHub에 있는 매니페스트를 클러스터에 적용
        automated:
            # GitHub에서 삭제된 리소스는 클러스터에서도 자동 삭제
            prune: true
            # 클러스터 안에서 수동으로 리소스가 변경되면, GitHub에 있는 원래 상태로 자동 복구
            selfHeal: true
