eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/ # 로컬에서는 유레카를 사용할 것이기 때문에 유레카 url을 명시해놓음.
spring:
    config:
        activate:
            on-profile: local
    application:
        name: api-gateway
    cloud:
        gateway:
            #      CORS 처리. 서비스모듈에서는 웹브라우저와 직접 통신하지 않으므로, cors처리 불필요.
            globalcors:
                cors-configurations:
                    "[/**]":
                        allowedOrigins:
                            - "http://localhost:3000" # local에서는 프런트가 당연히 localhost:3000 or 8080 이기 때문에 이런 형식을 설정
                        #              - 'https://www.example.com'
                        allowedMethods: "*"
                        allowedHeaders: "*"
                        allowedCredentials: true
            routes:
                - id: member-service
                  predicates:
                      - Path=/member-service/** # /member-service/* 로 들어오면~
                  filters:
                      # StripPrefix : 첫번째 접두어를 제거후에 member-service로 http요청 전달
                      - StripPrefix=1
                  uri: lb://member-service # 유레카에게 질의를 해서 해당 서비스쪽으로 이동
                - id: ordering-service
                  predicates:
                      - Path=/ordering-service/**
                  filters:
                      - StripPrefix=1
                  uri: lb://ordering-service
                - id: product-service
                  predicates:
                      - Path=/product-service/**
                  filters:
                      - StripPrefix=1
                  uri: lb://product-service
jwt:
    secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
